@cookie = accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZhNTNhYjA5ZmMwNTM1MTAyODJkNDMiLCJlbWFpbCI6ImtyaXNAaW50cm9kdWNlLmd1cnUiLCJpYXQiOjE2NTE1MDI4MTMsImV4cCI6MTY1MjEwMjc1M30.hooTAqxdDEjF8YE39bTpFAmDQoYyb7qdTxdwk1vFiIY

### Create One
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
    "firstName": "Kris",
    "lastName": "Zima",
    "fullName": "Kris Zima",
    "contactEmail": "kris@mosquito.ie",
    "contactPhone": "040404040",
    "businessName": "Kris & Co",
    "businessCategory": "Software",
    "stripeId": "",
    "abn": "",
    "addressLine1": "Address line 1",
    "addressLine2": "Address line 2",
    "city": "",
    "state": "AU",
    "country": "AU",
    "rating": 0,
    "successfulRate": 0,
    "averageCommission": 0,
    "commissionCurrency": "AUD",
    "commissionType": "",
    "commissionValue": 0,
    "commissionPerReceivedLead": 0,
    "commissionPerCompletedLead": 0,
    "commissionPerCompletedLeadPercent": 0,
    "isAcceptingIntroductions": false,
    "isActive": true,
    "isComplete": false
}

### Search
GET http://localhost:3000/api/users?q=kr HTTP/1.1
Cookie: {{cookie}}

### Find One
GET http://localhost:3000/api/users/626a53ab09fc053510282d43 HTTP/1.1
Cookie: {{cookie}}

### Update
PUT http://localhost:3000/api/users/626a53ab09fc053510282d43 HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
    "_id": "626a53ab09fc053510282d43",
    "firstName": "Kriso",
    "lastName": "Zima",
    "fullName": "Kris Zima",
    "contactEmail": "kris@mosquito.ie"
}

### Commission
GET http://localhost:3000/api/users/626a53ab09fc053510282d43/commission HTTP/1.1
Cookie: {{cookie}}