@intorductionId = 627c21f87e3c7c03fb11c0fa

### Create One
POST {{baseUrl}}/api/introductions HTTP/1.1
content-type: application/json
Cookie: {{accessToken}}

{
    "agreement": {
        "_id": "6270c5ba6a488c0261684240"
    },
    "business": {
        "userId": "626a53ab09fc053510282d43"
    },
    "guru": {
        "userId": "626a53ab09fc053510282d43"
    },
    "customer": {
        "userId": "626a53ab09fc053510282d43",
        "firstName": "Kris",
        "lastName": "Zima",
        "fullName": "Kris Zima",
        "contactEmail": "kris@guru.com"
    }
}

### Search
GET {{baseUrl}}/api/introductions HTTP/1.1
Cookie: {{accessToken}}

### Find One
GET {{baseUrl}}/api/introductions/{{intorductionId}} HTTP/1.1
Cookie: {{accessToken}}

### getQuote
GET {{baseUrl}}/api/introductions/{{intorductionId}}/quote HTTP/1.1
Cookie: {{accessToken}}

### Update
PUT {{baseUrl}}/api/introductions/{{intorductionId}} HTTP/1.1
content-type: application/json
Cookie: {{accessToken}}

{
    "status": "active"
}

