### Create One
POST {{baseUrl}}/api/agreements HTTP/1.1
content-type: application/json
Cookie: {{accessToken}}

{
    "guruId": "626a53ab09fc053510282d43",
    "businessId": "626a53ab09fc053510282d43",
    "commissionCurrency": "AUD",
    "commissionType": "fixed",
    "commissionPaymentType": "prepaid",
    "commissionValue": 7
}

### Search
GET {{baseUrl}}/api/agreements?guruId=626a53ab09fc053510282d43&businessId=626a53ab09fc053510282d77 HTTP/1.1
Cookie: {{accessToken}}

### Find One
GET {{baseUrl}}/api/agreements/6270c67d6a488c0261684242 HTTP/1.1
Cookie: {{accessToken}}


### Update
PUT {{baseUrl}}/api/agreements/6270c67d6a488c0261684242 HTTP/1.1
content-type: application/json
Cookie: {{accessToken}}

{
    "commissionValue": 8
}

